repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [--config=black.toml]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 9feadeb
    hooks:
    - id: mypy
      args: [--ignore-missing-imports, --warn-no-return, --warn-redundant-casts, --disallow-incomplete-defs]
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.9'
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-bugbear==19.8.0',
            'flake8-coding==1.3.2',
            'flake8-comprehensions==3.0.1',
            'flake8-debugger==3.2.1',
            'flake8-deprecated==1.3',
            'flake8-docstrings==1.5.0',
            'flake8-isort==2.7.0',
            'flake8-pep3101==1.2.1',
            'flake8-polyfill==1.0.2',
            'flake8-print==3.1.4',
            'flake8-quotes==2.1.1',
            'flake8-string-format==0.2.3',
        ]
