defaults:
  - dataset: wheat
  - trainer: default_trainer
  - training: default_training
  - logging: tensorboard
  - optimizer: adamw
  - scheduler: plateau
  - model: basic_fastrcnn
  - callbacks: callbacks
  - private: custom
  - data: data
  - augmentation: basic_augs

general:
  save_dir: logs/
  workspace: erlemar
  project_name: wheat
  device: cuda

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}
  sweep:
    dir: outputs/
    subdir: ${now:%Y_%m_%d_%H_%M_%S}
